### ISSUE TITLE
Plugin always applies an install hook regardless of the plugin being activated

### ISSUE THREAD

**Issue by kylef** [bugsnag/cocoapods-bugsnag#2]
The CocoaPods plugin will always run it's own custom install hook and apply to the user's Xcode project regardless of the cocoapods-bugsnag plugin being activated within a Podfile.
#### Steps to Reproduce
- Install the plugin `gem install cocoapods cocoapods-bugsnag`.
- Create an Xcode project and run `pod init` inside the directory containing Xcode.
- Run `pod install`
#### Expected Results

My user project does not have a Bugsnag hook installed. It should only be activated if I activate the plugin in my Podfile for CocoaPods.

``` ruby
plugin 'cocoapods-bugsnag'
```
#### Actual Result

My user project does have a Bugsnag hook installed.

**Comment by kattrali** [comment]
Thanks for the report, this should be an easy fix. I'm looking into it now.

**Comment by maurovc** [comment]
This is still happening. Do you have any update on this?

**Comment by mattdyoung** [comment]
@maurovc 
This hasn't been fixed yet. We'll take a fresh look and try to resolve when priorities allow.

Thanks.
