### ISSUE TITLE
How to use that?

### ISSUE THREAD

**Issue by SudoPlz** [bugsnag/cocoapods-bugsnag#3]
Is a build phase supposed to be created?

I have a hard time figuring out how to use that plugin.

I've installed the gem and then did a `pod install` but no luck yet.

**Comment by kattrali** [comment]
> Is a build phase supposed to be created?

Yep, it should all happen automatically. Are you using Bitcode in your app?

**Comment by SudoPlz** [comment]
Yeah, I am (and I'm not using fast lane).

Also I'm using buddybuild (CI) and I'm not building in my machine.

Also I already have that script in Xcode
```
fork do
Process.setsid
STDIN.reopen("/dev/null")
STDOUT.reopen("/dev/null", "a")
STDERR.reopen("/dev/null", "a")

require 'shellwords'

Dir["#{ENV["DWARF_DSYM_FOLDER_PATH"]}/*/Contents/Resources/DWARF/*"].each do |dsym|
system("curl -F dsym=@#{Shellwords.escape(dsym)} -F projectRoot=#{Shellwords.escape(ENV["PROJECT_DIR"])} https://upload.bugsnag.com/")
end
end
```

but it did nothing. I had no dsym files uploaded.

I had to go the the app store, download the dsym and upload it manually w/ `bugsnag-dsym-upload`.

I want to automate this process @kattrali .
(My Busnag acc is under `ioannis@acuityscheduling.com`)

Thanks.

**Comment by kattrali** [comment]
Okay, this won't work for you if you have bitcode enabled, since the dSYM files will be generated on apple's servers rather than the mac building the app ([more info here](https://docs.bugsnag.com/platforms/ios/symbolication-guide/#with-bitcode)).

**Comment by SudoPlz** [comment]
So how can I automate this process?

**Comment by kattrali** [comment]
With fastlane?

**Comment by SudoPlz** [comment]
Is there another way? (I don't really like fastlane) :/

**Comment by kattrali** [comment]
I'm right there with you, but as it currently stands automating interactions with the iTunes Connect "API" is non-trivial and hard to maintain as its more "scraping the current website"/"replicate what Xcode is doing" than a supported interface. The fastlane team has dedicated time and resources to staying on top of its changes, and it doesn't make much sense to spend those resources to do the same. There might be some other tools for this though.

**Comment by SudoPlz** [comment]
Ok, cool thank you for the responses @kattrali I really appreciate it.
Have a great weekend.

**Comment by kattrali** [comment]
Thank you :) Enjoy your weekend too @SudoPlz!
