### ISSUE TITLE
Missing Step

### ISSUE THREAD

**Issue by freddy1h** [bugsnag/cocoapods-bugsnag#5]
The script first tries to find the api key this way

`api_key = ENV["BUGSNAG_API_KEY"]
`

but I can't find any tutorials or installation docs that say we need to add an Environment variable named `BUGSNAG_API_KEY` and set the value to our key

Then the script tries to get the key from the Info.plist but I also can't find any tutorials or sections in the installation guide that say I should add the api key to my plist

```
# If not present, attempt to lookup the value from the Info.plist
if !api_key
  default_info_plist_location = Dir.glob("./{ios/,}*/Info.plist").reject {|path| path =~ /build|test/i }
  plist_buddy_response = `/usr/libexec/PlistBuddy -c "print :BugsnagAPIKey" "#{default_info_plist_location.first}"`
  api_key = plist_buddy_response if $?.success?
end
```

Since there are no instructions to add these values in either of these places, my dSYMs are NOT being uploaded so this plugin doesn't actually work.

**Comment by kattrali** [comment]
Thanks for the report, @freddy1h. I've updated the instructions to include setting your API key and the script to fail if no API key is specified.
