### ISSUE TITLE
Lock the http version when using curl

### ISSUE THREAD

**Issue by freddy1h** [bugsnag/cocoapods-bugsnag#7]
If you don't lock the http version to 1.1, the uploads will fail for larger files.

It has already been done here
[Bulk Upload Script](https://github.com/bugsnag/bugsnag-dsym-upload/commit/36ed9e91347fb11d8669028e0a61cc6005cdae2c)

Also, the upload will fail silently. At least, there should be a warning when the upload doesn't succeed.

**Comment by xljones** [comment]
Hi @freddy1h, thanks for letting us know about this. We'll get it updated!
